### ISSUE TITLE
material add 41005

### ISSUE THREAD

**Issue by hlltc** [Eric-Guo/wechat#63]
use material add to upload a image, always this error: 
block in request': media data missing hint: [HjjhHa0639ent1](41005) (Wechat::ResponseError)

any help? plz

**Comment by Eric-Guo** [comment]
Does it works if using `wechat` command line? using public account or enterprise account? any stack trace

**Comment by hlltc** [comment]
41005 no matter I use wechat command or wechat.material_add in .rb with a public account.
However, wechat.media_create is ok with the same account and same media file. But I want to upload a forever image material not a temp media.

**Comment by hlltc** [comment]
I also used `rest-client` to upload a material, and got 41005. 
But it succeeded when I used `postman` to add a material.
It seems to be a bug of wechat official API.

**Comment by Eric-Guo** [comment]
resolved at v0.6.3 by @hlltc himself at #67

**Comment by cestivan** [comment]
This problem still appears in 0.6.8. `wechat.media_create` is ok with the same account and same media file.

**Comment by Eric-Guo** [comment]
@cestivan can you try 0.6.9? material_add is break due to 0.7.0 using http instead of rest-client, but still have some problem in http gems.

**Comment by Eric-Guo** [comment]
for the http can not support material_add, there is #78 for it, so please using #78 instead of this one.
